# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

  gem 'sinatra'
  gem 'thin'
  gem 'require_all'
  gem 'activerecord', '5.2'
  gem 'sinatra-activerecord'
  gem 'rake'
  gem 'bcrypt'
  gem 'dotenv'
  gem 'sinatra-flash'

  group :development do
    gem 'shotgun'
    gem 'pry'
    gem 'tux'
    gem 'sqlite3', '~> 1.3.6'
    gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
  end 